name: "Cleanup Kluster"
description: "Destroy a kluster"
inputs:
  platform:
    description: "The platform the kluster ran tests for"
    required: true
  token:
    description: "The kubeception token to use"
    required: true
outputs: {}
runs:
  using: composite
  steps:
    - name: "Destroy cluster"
      shell: bash
      env:
        DEV_TELEPRESENCE_KUBECEPTION_TOKEN: ${{ inputs.token }}
      run: |
        # We don't allow the destroy to fail the build; if the kluster couldn't be destroyed now, it'll just be cleaned up when it times out
        go run ./build-aux/kubeception destroy "tp-ci-${{ inputs.platform }}-${GITHUB_SHA}" || true
