name: "Dev build"
on: [push]
jobs:
  "build_image":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.x'
      - name: Build dev image
        run: |
          TAG="2.0.0-gotest.$GITHUB_SHA"
          TELEPRESENCE_VERSION="v${TAG}" make image
          mkdir -p /tmp/workspace
          docker save "datawire/tel2:${TAG}" > tel2-image.tar
      - name: Upload image
        uses: actions/upload-artifact@v2
        with:
          name: image
          path: tel2-image.tar
  "linux_test":
    runs-on: ubuntu-latest
    needs: "build_image"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.x'
      - uses: azure/setup-kubectl@v1
        with:
          version: 'v1.19.3'
        id: kubectl
      - run: |
          sudo rm -f /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y sshfs
          sudo sh -c 'echo user_allow_other >> /etc/fuse.conf'
        name: install sshfs
      - uses: actions/download-artifact@v2
        with:
          name: image
      - uses: ./.github/actions/prepare-kluster
        with:
          platform: linux
          token: ${{ secrets.DEV_TELEPRESENCE_KUBECEPTION_TOKEN }}
          tel-image: tel2-image.tar
        id: kluster
      - run: |
          # We want to validate that tests still pass, even if the metrics host
          # points to a broken IP
          echo "127.0.0.1 metriton.datawire.io" | sudo tee -a /etc/hosts
          DTEST_KUBECONFIG="${{ steps.kluster.outputs.kubeconfig }}" DTEST_REGISTRY="docker.io/datawire" make test
      - uses: ./.github/actions/cleanup-kluster
        with:
          platform: linux
          token: ${{ secrets.DEV_TELEPRESENCE_KUBECEPTION_TOKEN }}
